spring:
  sleuth:
    enable: true

eureka:
  client:
    service-url:
      defaultZone: ${CLOUD_EUREKA_URI},${CLOUD_EUREKA_PEER_URI}
    register-with-eureka: true
    fetch-registry: true
  server:
    registry-sync-retries: 0
  instance:
    hostname: api-gateway
    securePortEnabled: true

zuul:
  retryable: true

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  IsSecure: true

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

info:
  port: $PORT
