spring:
  profile: ${EUREKA_INSTANCE}
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE}
  client:
    service-url:
      defaultZone: ${EUREKA_PEER_URL}
    register-with-eureka: true
    fetch-registry: true
  server:
    enableSelfPreservation: false
logging:
  level: debug

